name: default
on:
  - push
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ matrix.os == 'ubuntu-latest' && '~/.yarn/berry' || '%LOCALAPPDATA%\\Yarn\\Berry' }}
          key: ${{ runner.os }}-yarn
      - name: Install dependencies
        run: |
          corepack enable
          yarn set version latest
          yarn install --immutable
      - name: Run
        run: |
          cd packages/angular-workspace
          yarn run ng build angular-lib
          yarn run ng build demo-app
        continue-on-error: true
      - name: 'Run (nodeLinker: node-modules)'
        run: |
          yarn config set nodeLinker node-modules
          yarn install --immutable
          cd packages/angular-workspace
          yarn run ng build angular-lib
          yarn run ng build demo-app
